### ISSUE TITLE
关于您文章figure 3的分组问题

### ISSUE THREAD

**Issue by HeavenMountain** [yimutianyang/SIGIR23-VGCL#1]
尊敬的作者：

我对VGCL这篇文章的工作很感兴趣，但是在阅读实验部分的时候有一点困惑。您在4.4中将user分为四组，请问您的分组的方法或者说是分组的依据是什么呢？希望能得到您的解答。

祝好！

**Comment by yimutianyang** [comment]
Hi~感谢对我们工作的关注
图3中的用户分组是依据用户在训练集中的交互数量，按照由低到高分成4组。在文章中我们写到：Specifically, we first split all users into 4 groups according to their interactions。实现过程在rec_dataset.py 69行，具体的分组阈值在不同数据集会略有区别，大体思想是平衡各个组用户的数据基本一致。这个实验是为了证明在不同组上，赋予用户自监督的信号尺度是不一样的（由估计的方差决定）

**Comment by HeavenMountain** [comment]
我明白了，非常感谢您的回答。
