### ISSUE TITLE
关于实验参数的设置

### ISSUE THREAD

**Issue by yuanzhongfei** [yimutianyang/SIGIR23-VGCL#2]
您好，想咨询下关于论文数据集参数怎么设置的呢？论文里面有一部分，我调了一下，实验的结果好像有点问题，是不是还有其它参数设置呢？ 谢谢

**Comment by yimutianyang** [comment]
具体是指哪些数据集&参数呢？

**Comment by yuanzhongfei** [comment]
您好，是Movielens-25M和Dianping的运行参数设置

**Comment by yimutianyang** [comment]
抱歉，之前上传的ml-25m数据集有点问题，已更新
dianping和ml-25m的参数如下：
python run_VGCL.py --dataset dianping --gcn_layer 3 --alpha 0.05 --gamma 0.5 --temp_node 0.2 --temp_cluster 0.15 --num_user_cluster 500 --num_item_cluster 100
python run_VGCL.py --dataset ml25m --gcn_layer 3 --alpha 0.1 --gamma 1.0 --temp_node 0.2 --temp_cluster 0.08 --num_user_cluster 1200 --num_item_cluster 100 --batch_size 4096
我刚刚跑的结果：
dianping: recall@10=0.0779; ndcg@10=0.0615; 
ml-25m: recall@10=0.2458; ndcg@10=0.2400;

**Comment by yuanzhongfei** [comment]
非常感谢
