### ISSUE TITLE
关于kl散度的损失

### ISSUE THREAD

**Issue by akajinchen** [yimutianyang/SIGIR23-VGCL#3]
https://github.com/yimutianyang/SIGIR23-VGCL/blob/0b4bc7e216b4746f0f391f3a5f636efef3cd24f4/models/VGCL.py#L53C20-L53C82
这里的std不是logstd，为什么损失是当成logstd写的呢

**Comment by yimutianyang** [comment]
感谢指出，确实是写错了。我尝试了取logstd计算，其他参数不变的情况下调整beta系数(如douban: beta=0.1)，结果与原文差不多

**Comment by akajinchen** [comment]
好滴
