### ISSUE TITLE
论文中提及的图重建部分的代码在哪

### ISSUE THREAD

**Issue by Ricardo-Ping** [yimutianyang/SIGIR23-VGCL#4]
论文中提到了图重建生成，但是我在代码中没有发现这部分内容

**Comment by yimutianyang** [comment]
你好，图重建过程在line 64, self.compute_bpr_loss

**Comment by Ricardo-Ping** [comment]
您好，图重建过程就是BPR损失和正则化损失吗，我以为是重建图的邻接矩阵，另外一点是在你的代码中run_kmeans是先运行的forward得到user_emb和item_emb，然后在聚类的吗？因为NCL中是先进行的聚类然后进行前向。我在用pytorch框架重新复现代码，所以有点疑问

**Comment by yimutianyang** [comment]
1. 推荐可以看作图链接预测任务，BPR优化的是用户点击过的产品>未点击的产品，也就是约束相连的边的概率>未连接的边，跟图重构一样的；
2. 我用的是经过graph encoder之后的节点embedding做聚类的，跟NCL不太一样。直接用初始化的节点embedding做聚类也可以额，你可以自行尝试

**Comment by Ricardo-Ping** [comment]
好的，感谢！我已经将您的这篇代码进行复现，在我的主页的ChaoRec中，您有空可以指点一下是否存在问题

**Comment by yimutianyang** [comment]
好的，感谢对我们工作的关注！你的版本我没发现什么问题
另打个小广告，我们基于faiss检索加上numba加速的评估函数(evaluate.py)。不需要计算评分矩阵，对于评估大规模数据集非常好用，此外不依赖于tf或torch的库，拥有近乎c++的运行速度且内存需求小，也欢迎讨论~
