### ISSUE TITLE
关于vgae中重参数的系数

### ISSUE THREAD

**Issue by akajinchen** [yimutianyang/SIGIR23-VGCL#5]
https://github.com/yimutianyang/SIGIR23-VGCL/blob/0b4bc7e216b4746f0f391f3a5f636efef3cd24f4/models/VGCL.py#L44
你好，感谢你开源的代码和出色的工作，我看到了这里从标准差中采样是通过标准正态的noise实现，但是为什么要乘上0.01呢？

**Comment by yimutianyang** [comment]
传统的VAE是做图像任务的，input语义(encode目标)是非常明确的，VGAE同样也具有节点特征，只是说如何从feature space to latent space；但是CF里，节点embedding是不具备特征的，需要在训练过程中不断学习，给encoder带来了难度，所以我设置了这个系数控制方差尺度。0.01是经验参数，没做细粒度调参。

**Comment by akajinchen** [comment]
感谢
