### ISSUE TITLE
 在完整的安装 依赖包等 运行代码出现问题

### ISSUE THREAD

**Issue by gjk753** [yimutianyang/SIGIR23-VGCL#6]
python 3.8
faiss     1.7.2
tensorflow-gpu      2.2.0
cudatoolkit     10.1.168                   
cudnn        7.6.0
numpy          1.19.2
numba         0.55.1
抱错界面：

numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(DictType[int64,array(int64, 1d, A)]<iv=None>, int64, array(int32, 1d, C))
 
There are 16 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(DictType[int64,array(int64, 1d, A)]<iv=None>, int64, array(int32, 1d, C))':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'impl_setitem': File: numba\typed\dictobject.py: Line 674.
    With argument(s): '(DictType[int64,array(int64, 1d, A)]<iv=None>, int64, array(int32, 1d, C))':
   Rejected as the implementation raised a specific error:
     LoweringError: Failed in nopython mode pipeline (step: native lowering)
   expecting {i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]} but got {i8*, i8*, i64, i64, i32*, [1 x i64], [1 x i64]}

**Comment by yimutianyang** [comment]
你好，看起来是numba封装的数据类型与定义的不一致。
参考rec_dataset.py line 44-46, 定义的key, value类型是int64, 你这里输入的数据可能是int32
