### ISSUE TITLE
关于代码实现的问题

### ISSUE THREAD

**Issue by akajinchen** [yimutianyang/SIGIR23-VGCL#8]
您好，感谢您出色的工作和开源的代码，我想知道这份工作有pytorch的实现版本吗?

**Comment by yimutianyang** [comment]
hi，torch版本现已开源，欢迎使用。前段时间太忙了qaq

**Comment by akajinchen** [comment]
> hi，torch版本现已开源，欢迎使用。前段时间太忙了qaq

感谢~ 顺便好奇问一下 为什么pytorch版本会慢一点呢

**Comment by yimutianyang** [comment]
torch是动态图，速度应该是和tf2.0一样的。
tf 1.0是静态图，所有变量以及data flow是先定义好的，速度会快一些。缺点就是调试不方便

**Comment by akajinchen** [comment]
> torch是动态图，速度应该是和tf2.0一样的。
> tf 1.0是静态图，所有变量以及data flow是先定义好的，速度会快一些。缺点就是调试不方便

感谢指导~
